### ISSUE TITLE
Make available on Windows

### ISSUE THREAD

**Issue by zombiepigdragon** [zynthian/zynthian-emuface#1]
How can I find or build a Windows version of this?

**Comment by jofemodo** [comment]
You can`t ;-)
AFAIK, currently no one is working on a Windows port.

Anyway, you have to understand that zynthian-emuface is part of the Zynthian Development Environment and is not intended to be used by end users, but by developers.

It is assumed that Zynthian developers work on unix systems, mainly because Zynthian is a unix machine (linux).

Because of this reason, porting the emuface or any other part of zynthian to MS-Windows is not on Zynthian's roadmap and probably never will be.
